
/*
SodaCost                2    # Manufacturer Suggested Retail Price (MSRP) per bottle
NumStudents             2    # number of students to create
MaxPurchases            8    # maximum number of bottles a student purchases
NumVendingMachines      3    # number of vending machines
MaxStockPerFlavour      5    # maximum number of bottles of each flavour in a vending machine
MaxShippedPerFlavour    3    # maximum number of bottles of each flavour generated by the bottling
                             #    plant per production run
TimeBetweenShipments    3    # length of time between shipment pickup
ParentalDelay           2    # length of time between new deposits of funds
NumCouriers             1    # maximum number of couriers in the pool
*/

struct ConfigParms {
    unsigned int sodaCost;                 // MSRP per bottle
    unsigned int numStudents;              // number of students to create
    unsigned int maxPurchases;             // maximum number of bottles a student purchases
    unsigned int numVendingMachines;       // number of vending machines
    unsigned int maxStockPerFlavour;       // maximum number of bottles of each flavour stocked
    unsigned int maxShippedPerFlavour;     // number of bottles of each flavour in a shipment
    unsigned int timeBetweenShipments;     // length of time between shipment pickup
    unsigned int parentalDelay;            // length of time between cash deposits
    unsigned int numCouriers;              // number of couriers in the pool
};

void processConfigFile( const char *configFile, ConfigParms &cparms ) {
    // TODO
};

